apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  type: LoadBalancer   # Use NodePort if you don’t have a cloud LoadBalancer
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
